//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chatapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public class AudioMetadata implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public String sender;

    public String timestamp;

    public long size;

    public AudioMetadata()
    {
        this.sender = "";
        this.timestamp = "";
    }

    public AudioMetadata(String sender, String timestamp, long size)
    {
        this.sender = sender;
        this.timestamp = timestamp;
        this.size = size;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AudioMetadata r = null;
        if(rhs instanceof AudioMetadata)
        {
            r = (AudioMetadata)rhs;
        }

        if(r != null)
        {
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }
            if(this.size != r.size)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ChatApp::AudioMetadata");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, size);
        return h_;
    }

    public AudioMetadata clone()
    {
        AudioMetadata c = null;
        try
        {
            c = (AudioMetadata)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sender);
        ostr.writeString(this.timestamp);
        ostr.writeLong(this.size);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sender = istr.readString();
        this.timestamp = istr.readString();
        this.size = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, AudioMetadata v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public AudioMetadata ice_read(com.zeroc.Ice.InputStream istr)
    {
        AudioMetadata v = new AudioMetadata();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AudioMetadata> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, AudioMetadata v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<AudioMetadata> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(AudioMetadata.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final AudioMetadata _nullMarshalValue = new AudioMetadata();

    /** @hidden */
    public static final long serialVersionUID = 1678130856L;
}
