//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chatapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface ChatService extends com.zeroc.Ice.Object
{
    boolean sendPrivateMessage(String sender, String recipient, String message, com.zeroc.Ice.Current current);

    boolean sendGroupMessage(String sender, String groupName, String message, com.zeroc.Ice.Current current);

    boolean createGroup(String groupName, String[] members, com.zeroc.Ice.Current current);

    boolean deleteGroup(String groupName, com.zeroc.Ice.Current current);

    boolean addMemberToGroup(String groupName, String username, com.zeroc.Ice.Current current);

    boolean removeMemberFromGroup(String groupName, String username, com.zeroc.Ice.Current current);

    boolean sendVoiceNote(String sender, String recipient, AudioMetadata metadata, byte[] data, com.zeroc.Ice.Current current);

    boolean sendGroupVoiceNote(String sender, String groupName, byte[] data, com.zeroc.Ice.Current current);

    byte[] getAudioFromHistory(String fileName, com.zeroc.Ice.Current current);

    String initiateCall(String caller, String callee, com.zeroc.Ice.Current current);

    boolean answerCall(String callId, boolean accept, com.zeroc.Ice.Current current);

    void streamCallAudio(String callId, String sender, byte[] chunk, com.zeroc.Ice.Current current);

    boolean endCall(String callId, com.zeroc.Ice.Current current);

    String[] getConnectedUsers(com.zeroc.Ice.Current current);

    GroupInfo[] getAllGroups(com.zeroc.Ice.Current current);

    TextMessage[] getPrivateHistory(String user1, String user2, com.zeroc.Ice.Current current);

    TextMessage[] getGroupHistory(String groupName, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::ChatApp::ChatService",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::ChatApp::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendPrivateMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_sender;
        String iceP_recipient;
        String iceP_message;
        iceP_sender = istr.readString();
        iceP_recipient = istr.readString();
        iceP_message = istr.readString();
        inS.endReadParams();
        boolean ret = obj.sendPrivateMessage(iceP_sender, iceP_recipient, iceP_message, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_sender;
        String iceP_groupName;
        String iceP_message;
        iceP_sender = istr.readString();
        iceP_groupName = istr.readString();
        iceP_message = istr.readString();
        inS.endReadParams();
        boolean ret = obj.sendGroupMessage(iceP_sender, iceP_groupName, iceP_message, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String[] iceP_members;
        iceP_groupName = istr.readString();
        iceP_members = istr.readStringSeq();
        inS.endReadParams();
        boolean ret = obj.createGroup(iceP_groupName, iceP_members, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        boolean ret = obj.deleteGroup(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_addMemberToGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_username;
        iceP_groupName = istr.readString();
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.addMemberToGroup(iceP_groupName, iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_removeMemberFromGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_username;
        iceP_groupName = istr.readString();
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.removeMemberFromGroup(iceP_groupName, iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceNote(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_sender;
        String iceP_recipient;
        AudioMetadata iceP_metadata;
        byte[] iceP_data;
        iceP_sender = istr.readString();
        iceP_recipient = istr.readString();
        iceP_metadata = AudioMetadata.ice_read(istr);
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        boolean ret = obj.sendVoiceNote(iceP_sender, iceP_recipient, iceP_metadata, iceP_data, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupVoiceNote(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_sender;
        String iceP_groupName;
        byte[] iceP_data;
        iceP_sender = istr.readString();
        iceP_groupName = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        boolean ret = obj.sendGroupVoiceNote(iceP_sender, iceP_groupName, iceP_data, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAudioFromHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fileName;
        iceP_fileName = istr.readString();
        inS.endReadParams();
        byte[] ret = obj.getAudioFromHistory(iceP_fileName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeByteSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_initiateCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_caller;
        String iceP_callee;
        iceP_caller = istr.readString();
        iceP_callee = istr.readString();
        inS.endReadParams();
        String ret = obj.initiateCall(iceP_caller, iceP_callee, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_answerCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_callId;
        boolean iceP_accept;
        iceP_callId = istr.readString();
        iceP_accept = istr.readBool();
        inS.endReadParams();
        boolean ret = obj.answerCall(iceP_callId, iceP_accept, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_streamCallAudio(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_callId;
        String iceP_sender;
        byte[] iceP_chunk;
        iceP_callId = istr.readString();
        iceP_sender = istr.readString();
        iceP_chunk = istr.readByteSeq();
        inS.endReadParams();
        obj.streamCallAudio(iceP_callId, iceP_sender, iceP_chunk, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_endCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_callId;
        iceP_callId = istr.readString();
        inS.endReadParams();
        boolean ret = obj.endCall(iceP_callId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getConnectedUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getConnectedUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        GroupInfo[] ret = obj.getAllGroups(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GroupSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPrivateHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_user1;
        String iceP_user2;
        iceP_user1 = istr.readString();
        iceP_user2 = istr.readString();
        inS.endReadParams();
        TextMessage[] ret = obj.getPrivateHistory(iceP_user1, iceP_user2, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        TextMessage[] ret = obj.getGroupHistory(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "addMemberToGroup",
        "answerCall",
        "createGroup",
        "deleteGroup",
        "endCall",
        "getAllGroups",
        "getAudioFromHistory",
        "getConnectedUsers",
        "getGroupHistory",
        "getPrivateHistory",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "initiateCall",
        "removeMemberFromGroup",
        "sendGroupMessage",
        "sendGroupVoiceNote",
        "sendPrivateMessage",
        "sendVoiceNote",
        "streamCallAudio"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_addMemberToGroup(this, in, current);
            }
            case 1:
            {
                return _iceD_answerCall(this, in, current);
            }
            case 2:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 3:
            {
                return _iceD_deleteGroup(this, in, current);
            }
            case 4:
            {
                return _iceD_endCall(this, in, current);
            }
            case 5:
            {
                return _iceD_getAllGroups(this, in, current);
            }
            case 6:
            {
                return _iceD_getAudioFromHistory(this, in, current);
            }
            case 7:
            {
                return _iceD_getConnectedUsers(this, in, current);
            }
            case 8:
            {
                return _iceD_getGroupHistory(this, in, current);
            }
            case 9:
            {
                return _iceD_getPrivateHistory(this, in, current);
            }
            case 10:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 11:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 12:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 13:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 14:
            {
                return _iceD_initiateCall(this, in, current);
            }
            case 15:
            {
                return _iceD_removeMemberFromGroup(this, in, current);
            }
            case 16:
            {
                return _iceD_sendGroupMessage(this, in, current);
            }
            case 17:
            {
                return _iceD_sendGroupVoiceNote(this, in, current);
            }
            case 18:
            {
                return _iceD_sendPrivateMessage(this, in, current);
            }
            case 19:
            {
                return _iceD_sendVoiceNote(this, in, current);
            }
            case 20:
            {
                return _iceD_streamCallAudio(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
