//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chatapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean sendPrivateMessage(String sender, String recipient, String message)
    {
        return sendPrivateMessage(sender, recipient, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendPrivateMessage(String sender, String recipient, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendPrivateMessageAsync(sender, recipient, message, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendPrivateMessageAsync(String sender, String recipient, String message)
    {
        return _iceI_sendPrivateMessageAsync(sender, recipient, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendPrivateMessageAsync(String sender, String recipient, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendPrivateMessageAsync(sender, recipient, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_recipient -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendPrivateMessageAsync(String iceP_sender, String iceP_recipient, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendPrivateMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_recipient);
                     ostr.writeString(iceP_message);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean sendGroupMessage(String sender, String groupName, String message)
    {
        return sendGroupMessage(sender, groupName, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendGroupMessage(String sender, String groupName, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(sender, groupName, message, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String sender, String groupName, String message)
    {
        return _iceI_sendGroupMessageAsync(sender, groupName, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String sender, String groupName, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(sender, groupName, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_groupName -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendGroupMessageAsync(String iceP_sender, String iceP_groupName, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_message);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean createGroup(String groupName, String[] members)
    {
        return createGroup(groupName, members, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean createGroup(String groupName, String[] members, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, members, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String[] members)
    {
        return _iceI_createGroupAsync(groupName, members, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String[] members, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, members, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_members -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_createGroupAsync(String iceP_groupName, String[] iceP_members, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeStringSeq(iceP_members);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean deleteGroup(String groupName)
    {
        return deleteGroup(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean deleteGroup(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_deleteGroupAsync(groupName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteGroupAsync(String groupName)
    {
        return _iceI_deleteGroupAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteGroupAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_deleteGroupAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_deleteGroupAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean addMemberToGroup(String groupName, String username)
    {
        return addMemberToGroup(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean addMemberToGroup(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_addMemberToGroupAsync(groupName, username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> addMemberToGroupAsync(String groupName, String username)
    {
        return _iceI_addMemberToGroupAsync(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> addMemberToGroupAsync(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_addMemberToGroupAsync(groupName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_addMemberToGroupAsync(String iceP_groupName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addMemberToGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean removeMemberFromGroup(String groupName, String username)
    {
        return removeMemberFromGroup(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean removeMemberFromGroup(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_removeMemberFromGroupAsync(groupName, username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> removeMemberFromGroupAsync(String groupName, String username)
    {
        return _iceI_removeMemberFromGroupAsync(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> removeMemberFromGroupAsync(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_removeMemberFromGroupAsync(groupName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_removeMemberFromGroupAsync(String iceP_groupName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "removeMemberFromGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean sendVoiceNote(String sender, String recipient, AudioMetadata metadata, byte[] data)
    {
        return sendVoiceNote(sender, recipient, metadata, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendVoiceNote(String sender, String recipient, AudioMetadata metadata, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteAsync(sender, recipient, metadata, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendVoiceNoteAsync(String sender, String recipient, AudioMetadata metadata, byte[] data)
    {
        return _iceI_sendVoiceNoteAsync(sender, recipient, metadata, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendVoiceNoteAsync(String sender, String recipient, AudioMetadata metadata, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteAsync(sender, recipient, metadata, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_recipient -
     * @param iceP_metadata -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendVoiceNoteAsync(String iceP_sender, String iceP_recipient, AudioMetadata iceP_metadata, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceNote", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_recipient);
                     AudioMetadata.ice_write(ostr, iceP_metadata);
                     ostr.writeByteSeq(iceP_data);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean sendGroupVoiceNote(String sender, String groupName, byte[] data)
    {
        return sendGroupVoiceNote(sender, groupName, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendGroupVoiceNote(String sender, String groupName, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupVoiceNoteAsync(sender, groupName, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupVoiceNoteAsync(String sender, String groupName, byte[] data)
    {
        return _iceI_sendGroupVoiceNoteAsync(sender, groupName, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupVoiceNoteAsync(String sender, String groupName, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupVoiceNoteAsync(sender, groupName, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_groupName -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendGroupVoiceNoteAsync(String iceP_sender, String iceP_groupName, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupVoiceNote", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_groupName);
                     ostr.writeByteSeq(iceP_data);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default byte[] getAudioFromHistory(String fileName)
    {
        return getAudioFromHistory(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default byte[] getAudioFromHistory(String fileName, java.util.Map<String, String> context)
    {
        return _iceI_getAudioFromHistoryAsync(fileName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<byte[]> getAudioFromHistoryAsync(String fileName)
    {
        return _iceI_getAudioFromHistoryAsync(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<byte[]> getAudioFromHistoryAsync(String fileName, java.util.Map<String, String> context)
    {
        return _iceI_getAudioFromHistoryAsync(fileName, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<byte[]> _iceI_getAudioFromHistoryAsync(String iceP_fileName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<byte[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAudioFromHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fileName);
                 }, istr -> {
                     byte[] ret;
                     ret = istr.readByteSeq();
                     return ret;
                 });
        return f;
    }

    default String initiateCall(String caller, String callee)
    {
        return initiateCall(caller, callee, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String initiateCall(String caller, String callee, java.util.Map<String, String> context)
    {
        return _iceI_initiateCallAsync(caller, callee, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> initiateCallAsync(String caller, String callee)
    {
        return _iceI_initiateCallAsync(caller, callee, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> initiateCallAsync(String caller, String callee, java.util.Map<String, String> context)
    {
        return _iceI_initiateCallAsync(caller, callee, context, false);
    }

    /**
     * @hidden
     * @param iceP_caller -
     * @param iceP_callee -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_initiateCallAsync(String iceP_caller, String iceP_callee, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "initiateCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_caller);
                     ostr.writeString(iceP_callee);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default boolean answerCall(String callId, boolean accept)
    {
        return answerCall(callId, accept, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean answerCall(String callId, boolean accept, java.util.Map<String, String> context)
    {
        return _iceI_answerCallAsync(callId, accept, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> answerCallAsync(String callId, boolean accept)
    {
        return _iceI_answerCallAsync(callId, accept, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> answerCallAsync(String callId, boolean accept, java.util.Map<String, String> context)
    {
        return _iceI_answerCallAsync(callId, accept, context, false);
    }

    /**
     * @hidden
     * @param iceP_callId -
     * @param iceP_accept -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_answerCallAsync(String iceP_callId, boolean iceP_accept, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "answerCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_callId);
                     ostr.writeBool(iceP_accept);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void streamCallAudio(String callId, String sender, byte[] chunk)
    {
        streamCallAudio(callId, sender, chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void streamCallAudio(String callId, String sender, byte[] chunk, java.util.Map<String, String> context)
    {
        _iceI_streamCallAudioAsync(callId, sender, chunk, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> streamCallAudioAsync(String callId, String sender, byte[] chunk)
    {
        return _iceI_streamCallAudioAsync(callId, sender, chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> streamCallAudioAsync(String callId, String sender, byte[] chunk, java.util.Map<String, String> context)
    {
        return _iceI_streamCallAudioAsync(callId, sender, chunk, context, false);
    }

    /**
     * @hidden
     * @param iceP_callId -
     * @param iceP_sender -
     * @param iceP_chunk -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_streamCallAudioAsync(String iceP_callId, String iceP_sender, byte[] iceP_chunk, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "streamCallAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_callId);
                     ostr.writeString(iceP_sender);
                     ostr.writeByteSeq(iceP_chunk);
                 }, null);
        return f;
    }

    default boolean endCall(String callId)
    {
        return endCall(callId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean endCall(String callId, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(callId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> endCallAsync(String callId)
    {
        return _iceI_endCallAsync(callId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> endCallAsync(String callId, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(callId, context, false);
    }

    /**
     * @hidden
     * @param iceP_callId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_endCallAsync(String iceP_callId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_callId);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String[] getConnectedUsers()
    {
        return getConnectedUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getConnectedUsers(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync()
    {
        return _iceI_getConnectedUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getConnectedUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConnectedUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default GroupInfo[] getAllGroups()
    {
        return getAllGroups(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default GroupInfo[] getAllGroups(java.util.Map<String, String> context)
    {
        return _iceI_getAllGroupsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<GroupInfo[]> getAllGroupsAsync()
    {
        return _iceI_getAllGroupsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<GroupInfo[]> getAllGroupsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllGroupsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<GroupInfo[]> _iceI_getAllGroupsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<GroupInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllGroups", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     GroupInfo[] ret;
                     ret = GroupSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default TextMessage[] getPrivateHistory(String user1, String user2)
    {
        return getPrivateHistory(user1, user2, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default TextMessage[] getPrivateHistory(String user1, String user2, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateHistoryAsync(user1, user2, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<TextMessage[]> getPrivateHistoryAsync(String user1, String user2)
    {
        return _iceI_getPrivateHistoryAsync(user1, user2, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<TextMessage[]> getPrivateHistoryAsync(String user1, String user2, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateHistoryAsync(user1, user2, context, false);
    }

    /**
     * @hidden
     * @param iceP_user1 -
     * @param iceP_user2 -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<TextMessage[]> _iceI_getPrivateHistoryAsync(String iceP_user1, String iceP_user2, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<TextMessage[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPrivateHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_user1);
                     ostr.writeString(iceP_user2);
                 }, istr -> {
                     TextMessage[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default TextMessage[] getGroupHistory(String groupName)
    {
        return getGroupHistory(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default TextMessage[] getGroupHistory(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupHistoryAsync(groupName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<TextMessage[]> getGroupHistoryAsync(String groupName)
    {
        return _iceI_getGroupHistoryAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<TextMessage[]> getGroupHistoryAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupHistoryAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<TextMessage[]> _iceI_getGroupHistoryAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<TextMessage[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     TextMessage[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ChatApp::ChatService";
    }
}
