//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chatapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

/**
 * Helper class for marshaling/unmarshaling MessageSeq.
 **/
public final class MessageSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, TextMessage[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                TextMessage.ice_write(ostr, v[i0]);
            }
        }
    }

    public static TextMessage[] read(com.zeroc.Ice.InputStream istr)
    {
        final TextMessage[] v;
        final int len0 = istr.readAndCheckSeqSize(3);
        v = new TextMessage[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = TextMessage.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<TextMessage[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, TextMessage[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            MessageSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<TextMessage[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            TextMessage[] v;
            v = MessageSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
