//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chatapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public class TextMessage implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String sender;

    public String content;

    public String timestamp;

    public TextMessage()
    {
        this.sender = "";
        this.content = "";
        this.timestamp = "";
    }

    public TextMessage(String sender, String content, String timestamp)
    {
        this.sender = sender;
        this.content = content;
        this.timestamp = timestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        TextMessage r = null;
        if(rhs instanceof TextMessage)
        {
            r = (TextMessage)rhs;
        }

        if(r != null)
        {
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.content != r.content)
            {
                if(this.content == null || r.content == null || !this.content.equals(r.content))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ChatApp::TextMessage");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, content);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        return h_;
    }

    public TextMessage clone()
    {
        TextMessage c = null;
        try
        {
            c = (TextMessage)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sender);
        ostr.writeString(this.content);
        ostr.writeString(this.timestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sender = istr.readString();
        this.content = istr.readString();
        this.timestamp = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, TextMessage v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public TextMessage ice_read(com.zeroc.Ice.InputStream istr)
    {
        TextMessage v = new TextMessage();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<TextMessage> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, TextMessage v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<TextMessage> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(TextMessage.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final TextMessage _nullMarshalValue = new TextMessage();

    /** @hidden */
    public static final long serialVersionUID = 800576105L;
}
