# Activar IceSSL
Ice.Plugin.IceSSL=IceSSL:createIceSSL

# Ruta al keystore (relativa al cwd del proceso)
IceSSL.Keystore=C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\conf\\keystore.jks
IceSSL.Password=chatApp

# Opcional: fuerza TLS moderno
IceSSL.Protocols=TLS1_2
